### ISSUE TITLE
Unable to drop

### ISSUE THREAD

**Issue by billsaysthis** [mikeplate/jquery-drag-drop-plugin#3]
Love the simplicity and felxibility of your plugin but I'm having an issue with drops.

The source-related CSS and functions work as expected but the drop-related do not; that is, the CSS class never appears and I don't see the alert message, including if I add a canDrop callback.

Using latest versions of Chrome and Firefox on OSX 10.6

``` html
<ul class="unstyled draggable">
  <li id="opt_qu_0" class="">comments</li>
  <li id="opt_qu_1" class="">Name</li>
  <li id="opt_qu_2" class="">jobTitle</li>
  <li id="opt_qu_3" class="">phone</li>
</ul>

<ul class="unstyled drop" id="idOrderingList">
  <li id="inc_qu_0" class="">Ultimate Question</li>
  <li id="inc_qu_1" class="">Email</li>
  <li id="inc_qu_2" class="">product1</li>
</ul>
```

``` javascript
$(function () {
  $('.draggable').dragdrop({
    sourceHide: true,
    dragClass: "whileDragging",
    canDropClass: 'hilightDropped',
    dropClass: 'hilightDropped',
    didDrop: function($src, $dst) {
      alert('dropped '+$src.text());
    }
  });
});
```

**Comment by mikeplate** [comment]
I'm very happy you like it! I think the fault here might be that my documentation is lacking. I haven't explained the difference between dropClass and canDropClass enough (or, at all, really). Please test the following and let me know if it works and I'll update the readme.

Remove the dropClass setting, thereby letting the default "drop" be used, or set it to "drop" and not "hilightDropped". The dropClass is what the plugin uses to identify if a dragged element can be dropped on a particular element . And since the html doesn't have any "hilightDropped" class applied anywhere from the start, you can't drop an element at all.

Maybe the names of these properties are simply a little confusing. I think you've used the "canDropClass" as I intended. That class is applied to the droppable area once a dragged element is above it to indicate that a drop is valid there.

**Comment by billsaysthis** [comment]
I changed the JS to just this but have the same result:

``` javascript
$('.draggable').dragdrop({
  sourceHide: true,
  dragClass: "whileDragging",
  didDrop: function($src, $dst) {
    alert('dropped '+$src.text());
  }
});
```

**Comment by billsaysthis** [comment]
Sorry, hit the wrong submit button.

**Comment by mikeplate** [comment]
Great, I think I see my bug now. Either the droppable element has to be empty (no child elements), or the container can only have a single class of "drop" (and not, in your example, "unstyled" too). So it should work if you can live without the "unstyled" class on the droppable ul element for now. I'll fix it tomorrow and close the issue once it is done.

**Comment by billsaysthis** [comment]
I changed the drop HTML so that the UL has a containing div with just that class (<div class="drop"><ul>...) but no difference in results.

I can wait for tomorrow to see what your fix comes up with.

Thanks!

**Comment by mikeplate** [comment]
Actually, I can't repeat your problem. I've pasted your html and plugin-call into a web page and published it as a gist https://gist.github.com/1300631

This example works fine, turning the droppable li-elements orange when hovering over them while dragging. Please feel free to paste in your own complete html in the gist and I'll look at why it is not working.
